# Generated by Django 6.0.6 on 2026-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='projects/')),
                ('github', models.URLField()),
                ('video_demo', models.URLField()),
                ('tecnologias', models.CharField(max_length=200)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
